// This file is auto-generated using scripts/generate-index.ts
// Do not edit this file manually.

export interface SiteMetadata {
  name: string;
  slug: string;
  url: string;
  description: string;
  category: string;
  tags: string[];
  aesthetics: string[];
  effects: string[];
  typography: string[];
  composition: string[];
  colorScheme: string[];
  interaction: string[];
  featured: boolean;
  thumbnail: string;
  images: string[];
  date: string;
  socialLink?: string;
}

export const sites: SiteMetadata[] = [
  {
    "name": "Raycast",
    "slug": "raycast",
    "url": "https://raycast.com",
    "description": "A radically faster and better way to work on your Mac",
    "category": "landing page",
    "tags": [
      "hardware",
      "tools",
      "mac"
    ],
    "aesthetics": [
      "futuristic",
      "dark"
    ],
    "effects": [
      "gradients",
      "glassmorphism",
      "glow"
    ],
    "typography": [
      "sans-serif",
      "monospace"
    ],
    "composition": [
      "bento",
      "full-bleed"
    ],
    "colorScheme": [
      "dark-mode",
      "neon",
      "high-contrast"
    ],
    "interaction": [
      "scroll-animations",
      "page-transitions",
      "cursor-effects"
    ],
    "featured": true,
    "thumbnail": "/images/aceternity.png",
    "images": [
      "/images/aceternity.png"
    ],
    "date": "2026-03-05",
    "socialLink": "https://x.com/raycastapp"
  },
  {
    "name": "Opal Camera",
    "slug": "opal-camera",
    "url": "https://opalcamera.com",
    "description": "The first professional webcam for your Mac",
    "category": "landing page",
    "tags": [
      "hardware",
      "consumer",
      "photography"
    ],
    "aesthetics": [
      "industrial",
      "premium",
      "minimalism"
    ],
    "effects": [
      "3d",
      "parallax",
      "video"
    ],
    "typography": [
      "sans-serif",
      "display"
    ],
    "composition": [
      "full-bleed",
      "centered",
      "hero"
    ],
    "colorScheme": [
      "monochrome",
      "high-contrast",
      "dark-mode"
    ],
    "interaction": [
      "scroll-animations",
      "video-playback",
      "page-transitions"
    ],
    "featured": true,
    "thumbnail": "/images/shadcn.png",
    "images": [
      "/images/shadcn.png"
    ],
    "date": "2026-03-12",
    "socialLink": "https://x.com/opalcamera"
  },
  {
    "name": "Notion",
    "slug": "notion",
    "url": "https://notion.so",
    "description": "Your connected workspace for wiki, docs & projects",
    "category": "product design",
    "tags": [
      "saas",
      "productivity",
      "workspace"
    ],
    "aesthetics": [
      "minimalism",
      "editorial",
      "clean"
    ],
    "effects": [],
    "typography": [
      "serif",
      "sans-serif"
    ],
    "composition": [
      "sidebar",
      "whitespace",
      "blocks"
    ],
    "colorScheme": [
      "light-mode",
      "dark-mode",
      "muted"
    ],
    "interaction": [
      "drag-and-drop",
      "hover-effects"
    ],
    "featured": false,
    "thumbnail": "/images/shadcn.png",
    "images": [
      "/images/shadcn.png"
    ],
    "date": "2026-02-15",
    "socialLink": "https://x.com/NotionHQ"
  },
  {
    "name": "Tailwind UI",
    "slug": "tailwind-ui",
    "url": "https://tailwindui.com",
    "description": "Beautifully designed, fully responsive UI components",
    "category": "product design",
    "tags": [
      "components",
      "ui-kit",
      "design-system"
    ],
    "aesthetics": [
      "clean",
      "accessible",
      "modern"
    ],
    "effects": [
      "shadows",
      "blur"
    ],
    "typography": [
      "sans-serif",
      "inter"
    ],
    "composition": [
      "grid",
      "cards",
      "whitespace"
    ],
    "colorScheme": [
      "light-mode",
      "dark-mode"
    ],
    "interaction": [
      "hover-effects",
      "transitions"
    ],
    "featured": false,
    "thumbnail": "/images/aceternity.png",
    "images": [
      "/images/aceternity.png"
    ],
    "date": "2026-03-10",
    "socialLink": "https://x.com/tailwindcss"
  },
  {
    "name": "Cron",
    "slug": "cron",
    "url": "https://cron.com",
    "description": "The next-generation calendar for professionals and teams",
    "category": "product design",
    "tags": [
      "saas",
      "productivity",
      "calendar"
    ],
    "aesthetics": [
      "minimalism",
      "swiss",
      "clean"
    ],
    "effects": [
      "blur"
    ],
    "typography": [
      "sans-serif",
      "inter"
    ],
    "composition": [
      "sidebar",
      "grid",
      "whitespace"
    ],
    "colorScheme": [
      "light-mode",
      "monochrome",
      "accessible"
    ],
    "interaction": [
      "micro-interactions",
      "keyboard-shortcuts",
      "drag-and-drop"
    ],
    "featured": true,
    "thumbnail": "/images/shadcn.png",
    "images": [
      "/images/shadcn.png"
    ],
    "date": "2026-03-01",
    "socialLink": "https://x.com/cron"
  },
  {
    "name": "Aceternity UI",
    "slug": "aceternity-ui",
    "url": "https://ui.aceternity.com",
    "description": "Animated React component library with stunning visual effects",
    "category": "product design",
    "tags": [
      "animated",
      "components"
    ],
    "aesthetics": [
      "futuristic",
      "glassmorphism"
    ],
    "effects": [
      "gradients",
      "blur",
      "3d",
      "parallax"
    ],
    "typography": [
      "sans-serif",
      "display"
    ],
    "composition": [
      "grid",
      "bento",
      "full-bleed"
    ],
    "colorScheme": [
      "dark-mode",
      "vibrant",
      "neon"
    ],
    "interaction": [
      "scroll-animations",
      "hover-effects",
      "micro-interactions",
      "cursor-effects"
    ],
    "featured": true,
    "thumbnail": "/images/aceternity.png",
    "images": [
      "/images/aceternity.png"
    ],
    "date": "2026-01-01",
    "socialLink": "https://x.com/aceternityui"
  }
];
