// This file is auto-generated using scripts/generate-index.ts
// Do not edit this file manually.

export interface SiteMetadata {
  name: string;
  slug: string;
  url: string;
  description: string;
  category: string;
  tags: string[];
  tech: string[];
  platform: string[];
  animation: string[];
  style: string[];
  color: string[];
  layout: string[];
  featured: boolean;
  thumbnail: string;
  images: string[];
  date: string;
}

export const sites: SiteMetadata[] = [
  {
    "name": "shadcn/ui",
    "slug": "shadcn-ui",
    "url": "https://ui.shadcn.com",
    "description": "Beautifully designed components that you can copy and paste into your apps",
    "category": "tools",
    "tags": [
      "react",
      "nextjs",
      "accessible"
    ],
    "tech": [
      "react",
      "nextjs",
      "radix-ui"
    ],
    "platform": [
      "custom"
    ],
    "animation": [
      "css"
    ],
    "style": [
      "minimal",
      "clean"
    ],
    "color": [
      "light",
      "dark"
    ],
    "layout": [
      "grid"
    ],
    "featured": true,
    "thumbnail": "/images/shadcn.png",
    "images": ["/images/shadcn.png"],
    "date": "2026-01-15"
  },
  {
    "name": "Aceternity UI",
    "slug": "aceternity-ui",
    "url": "https://ui.aceternity.com",
    "description": "Animated React component library",
    "category": "tools",
    "tags": [
      "react",
      "nextjs",
      "animated"
    ],
    "tech": [
      "react",
      "nextjs"
    ],
    "platform": [
      "custom"
    ],
    "animation": [
      "framer-motion"
    ],
    "style": [
      "minimal",
      "modern"
    ],
    "color": [
      "dark"
    ],
    "layout": [
      "grid"
    ],
    "featured": true,
    "thumbnail": "/images/aceternity.png",
    "images": ["/images/aceternity.png"],
    "date": "2026-01-01"
  }
];
