
import fs from 'fs';
import path from 'path';
import matter from 'gray-matter';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const CONTENT_DIR = path.join(__dirname, '../src/content/sites');
const OUTPUT_FILE = path.join(__dirname, '../src/content/sites/index.ts');

interface SiteMetadata {
  name: string;
  slug: string;
  url: string;
  description: string;
  category: string;
  tags: string[];
  aesthetics: string[];
  effects: string[];
  typography: string[];
  composition: string[];
  colorScheme: string[];
  interaction: string[];
  featured: boolean;
  thumbnail: string;
  images: string[];
  date: string;
  socialLink?: string;
}

function generateIndex() {
  if (!fs.existsSync(CONTENT_DIR)) {
    console.error(`Content directory not found: ${CONTENT_DIR}`);
    process.exit(1);
  }

  const files = fs.readdirSync(CONTENT_DIR).filter(file => file.endsWith('.mdx'));
  const sites: SiteMetadata[] = [];

  for (const file of files) {
    const filePath = path.join(CONTENT_DIR, file);
    const content = fs.readFileSync(filePath, 'utf-8');
    const { data } = matter(content);

    // Validate required fields (basic check)
    if (!data.name || !data.slug) {
      console.warn(`Missing required metadata in ${file}`);
      continue;
    }

    sites.push(data as SiteMetadata);
  }

  const fileContent = `// This file is auto-generated using scripts/generate-index.ts
// Do not edit this file manually.

export interface SiteMetadata {
  name: string;
  slug: string;
  url: string;
  description: string;
  category: string;
  tags: string[];
  aesthetics: string[];
  effects: string[];
  typography: string[];
  composition: string[];
  colorScheme: string[];
  interaction: string[];
  featured: boolean;
  thumbnail: string;
  images: string[];
  date: string;
  socialLink?: string;
}

export const sites: SiteMetadata[] = ${JSON.stringify(sites, null, 2)};
`;

  fs.writeFileSync(OUTPUT_FILE, fileContent);
  console.log(`Generated sites index with ${sites.length} sites.`);
}

generateIndex();
